import {
  ChromeIcon,
  CodeIcon,
  ComponentIcon,
  DailyDevIcon,
  FirefoxIcon,
  GitHubIcon,
  HtmlIcon,
  JavaScriptIcon,
  JestIcon,
  LinkedInIcon,
  NextjsIcon,
  NodejsIcon,
  PhpIcon,
  ReactIcon,
  ResponsiveIcon,
  SassIcon,
  StackOverflowIcon,
  StorybookIcon,
  TestingLibraryIcon,
  TypeScriptIcon,
} from './Icons';

export const Icons = {
  Chrome: ChromeIcon,
  Code: CodeIcon,
  Component: ComponentIcon,
  DailyDev: DailyDevIcon,
  Firefox: FirefoxIcon,
  GitHub: GitHubIcon,
  Html: HtmlIcon,
  JavaScript: JavaScriptIcon,
  Jest: JestIcon,
  LinkedIn: LinkedInIcon,
  Nextjs: NextjsIcon,
  Nodejs: NodejsIcon,
  Php: PhpIcon,
  React: ReactIcon,
  Responsive: ResponsiveIcon,
  Sass: SassIcon,
  StackOverflow: StackOverflowIcon,
  Storybook: StorybookIcon,
  TestingLibrary: TestingLibraryIcon,
  TypeScript: TypeScriptIcon,
};

export type IconKeys = keyof typeof Icons;
